name = "ku-unity"
main = "worker.js"
compatibility_date = "2025-08-09"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

# 환경 변수는 wrangler secret put 명령어로 설정
# DATABASE_URL, JWT_SECRET, HASHSALT
